name: "assignment3-rnn-sweep"
method: "bayes"
project: da6401-assignment3
program: "train.py"
metric:
  name: val_acc
  goal: maximize
parameters:
  wandb_project:
    value: "da6401-assignment3"
  wandb_entity:
    value: "sjshiva8287"

  learning_rate:  
    distribution: uniform
    max: 1e-4
    min: 1e-6
  batch_size:
    values: [128, 256, 512]
  epochs:
    values: [20]
  layers:
    values: [2, 3, 4]
  cell:
    values: ["rnn", "lstm", "gru"]
  hidden_size:
    values: [64, 128, 256]
  input_embedding_size:
    values: [64, 128, 256]
  bidirectional:
    values: [0, 1]
  encoder_dropout:
    distribution: uniform
    max: 0.3
    min: 0.1
  decoder_dropout:
    distribution: uniform
    max: 0.3
    min: 0.1

  target_embed_dim:
    values: [32, 64, 128]
  dropout:
    distribution: uniform
    min: 0.1
    max: 0.5
  teacher_forcing_ratio:
    distribution: uniform
    min: 0.2
    max: 0.8
  grad_clip_val:
    values: [0.0, 1.0, 5.0]
  label_smoothing:
    distribution: uniform
    min: 0.0
    max: 0.2
